application: me-memo
version: 1
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /console/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /media
  static_dir: media
  secure: optional

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional
